version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - env
      - aws --version
      #aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 067726513902.dkr.ecr.us-east-1.amazonaws.com
      - $(aws ecr get-login --no-include-email $AWS_DEFAULT_REGION )
      #REPOSITORY_URI=067726513902.dkr.ecr.us-east-1.amazonaws.com/last
      # COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-10)
      #IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
      - docker tag $REPOSITORY_URI:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$DEFAULT_REGION.amazonaws.com/$$REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      #docker push $REPOSITORY_URI:latest
      #docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$DEFAULT_REGION.amazonaws.com/$$REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $AWS_ACCOUNT_ID.dkr.ecr.$DEFAULT_REGION.amazonaws.com/$$REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
