version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - env
      - aws --version
      - docker login --username saichaitanya2288 --password chaitanya@401
      - $(aws ecr get-login-password --region us-east-1) 
      #docker login --username AWS --password-stdin 067726513902.dkr.ecr.us-east-1.amazonaws.com
      - sudo systemctl start docker
      
      - REPOSITORY_URI=067726513902.dkr.ecr.us-east-1.amazonaws.com/interstellar1
      #COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-17)
      #IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest 067726513902.dkr.ecr.us-east-1.amazonaws.com/interstellar1
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      #docker push $REPOSITORY_URI:latest
      #docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push 067726513902.dkr.ecr.us-east-1.amazonaws.com/interstellar1
      - echo Writing image definitions file...
      - printf '[{"name":"nodecontainer","imageUri":"%s"}]' 067726513902.dkr.ecr.us-east-1.amazonaws.com/interstellar1:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
